version: "3.9"

services:
  # Component Libray
  components:
    build: .
    command: yarn storybook
    container_name: components
    environment:
      - VIRTUAL_HOST=mmcgrath.io
      - VIRTUAL_PATH=/components
      - VIRTUAL_PORT=3001
      - VIRTUAL_DEST=/
    ports:
      - 3001
    volumes:
      - .:/home/app
      - /node_modules
      - /.storybook

  # NextJS Portfolio
  portfolio:
    build: .
    command: yarn dev -p 443
    container_name: portfolio
    environment:
      - VIRTUAL_HOST=mmcgrath.io
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=443
      - DHPARAM_GENERATION=false
      - HTTPS_METHOD=nohttp
    ports:
      - 443
    volumes:
      - .:/home/app
      - /node_modules
      - /.next

  nginx-proxy:
    build:
      context: ./nginx-proxy/
      dockerfile: Dockerfile
    container_name: nginx-proxy
    depends_on:
      - components
      - portfolio
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/certs:/etc/nginx/certs

volumes:
  components:
  portfolio:

networks:
  default:
    name: mmdev
