version: "3.9"

services:
  # Component Libray
  components:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn storybook
    container_name: components
    environment:
      - VIRTUAL_HOST=components.mmcgrath.test
      - VIRTUAL_PORT=3001
    ports:
      - 3001
    volumes:
      - .:/home/app
      - /node_modules
      - /.storybook

  # NextJS Portfolio
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn dev
    container_name: portfolio
    environment:
      - VIRTUAL_HOST=mmcgrath.test
      - VIRTUAL_PORT=3000
    ports:
      - 3000
    volumes:
      - .:/home/app
      - /node_modules
      - /.next

volumes:
  components:
  portfolio:

networks:
  default:
    name: mmdev
