version: "3"

services:
  # Component Libray
  components:
    build: .
    command: yarn storybook
    container_name: components
    environment:
      - VIRTUAL_HOST=mmcgrath.io
      - VIRTUAL_PATH=/components
      - VIRTUAL_PORT=3001
      - VIRTUAL_DEST=/
    ports:
      - 3001
    volumes:
      - .:/app
      - .:/app:cached
      - node_modules:/app/node_modules
      - /.storybook
    networks:
      - mmdev

  # NextJS Portfolio
  portfolio:
    build: .
    command: yarn dev -p 443
    container_name: portfolio
    environment:
      - VIRTUAL_HOST=mmcgrath.io
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=443
    ports:
      - 443
    volumes:
      - .:/app
      - .:/app:cached
      - node_modules:/app/node_modules
      - /.next
    networks:
      - mmdev

  nginx-proxy:
    build:
      context: ./nginx-proxy/
      dockerfile: Dockerfile
    container_name: nginx-proxy
    depends_on:
      - components
      - portfolio
      - mongodb
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/certs:/etc/nginx/certs
    networks:
      - mmdev

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mmcgrath
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=portfolio
    networks:
      - mmdev

volumes:
  components:
  portfolio:
  nginx-proxy:
  node_modules:
  mongodb-data:

networks:
  mmdev:
    driver: bridge
