version: '3.3'

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /node_modules
      - /.next
    command: yarn dev

  components:
    ports:
      - 3001:3001
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /.storybook
    command: yarn storybook