version: "3.9"

services:
  # Component Libray
  components:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn storybook
    container_name: components
    ports:
      - 3001:3001
    volumes:
      - .:/home/app
      - /node_modules
      - /.storybook

  # NextJS Portfolio
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn dev
    container_name: portfolio
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
      - /node_modules
      - /.next
